using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EnterpriseAuth.Api.Core.Domain.Entities
{
    [Table("LabelAudits")]
    public class LabelAudit
    {
        [Key]
        [Column("Id")]
        public Guid Id { get; set; } = Guid.NewGuid();

        [Required]
        [MaxLength(50)]
        [Column("LabelId")]
        public string LabelId { get; set; } = string.Empty; // e.g. LBL-260416-0001 or OFF-LBL-...

        [MaxLength(100)]
        [Column("ReferenceNumber")]
        public string? ReferenceNumber { get; set; } // SO Number or Crate/Palette ID

        [MaxLength(50)]
        [Column("LabelType")]
        public string? LabelType { get; set; } // ITEM, CRATE, PALETTE

        [MaxLength(100)]
        [Column("ProductCode")]
        public string? ProductCode { get; set; }

        [MaxLength(200)]
        [Column("CustomerName")]
        public string? CustomerName { get; set; }

        [Column("TotalWeight")]
        public decimal TotalWeight { get; set; }

        [Column("ManifestJson")]
        public string? ManifestJson { get; set; } // Serialization of manifest items

        [MaxLength(100)]
        [Column("PrintedBy")]
        public string? PrintedBy { get; set; }

        [Column("CreatedAt")]
        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

        [Column("IsOfflineCreated")]
        public bool IsOfflineCreated { get; set; } // True if generated by mobile app while offline

        [MaxLength(100)]
        [Column("DeviceId")]
        public string? DeviceId { get; set; }
    }
}
