// <auto-generated />
using System;
using EnterpriseAuth.Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EnterpriseAuth.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ScanProductionDbContext))]
    partial class ScanProductionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EnterpriseAuth.Api.Core.Domain.Entities.AuditLog", b =>
                {
                    b.Property<int>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AuditId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuditId"));

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("ActionType");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("DeviceId");

                    b.Property<string>("EntityIdString")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("EntityIdString");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("EntityName");

                    b.Property<string>("Payload")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Payload");

                    b.Property<DateTime>("PerformedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("PerformedAt");

                    b.Property<string>("PerformedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("PerformedBy");

                    b.HasKey("AuditId");

                    b.HasIndex("EntityName", "EntityIdString")
                        .HasDatabaseName("IX_AuditLogs_EntityLookup");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("EnterpriseAuth.Api.Core.Domain.Entities.EodProcessAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("EodDate")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeactivated")
                        .HasColumnType("bit");

                    b.Property<string>("TriggeredBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("WorkOrderNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("EodProcessAudits");
                });

            modelBuilder.Entity("EnterpriseAuth.Api.Core.Domain.Entities.Excess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AllocatedQuantity")
                        .HasPrecision(18, 5)
                        .HasColumnType("decimal(18,5)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("ExcludeFromEod")
                        .HasColumnType("bit");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("RemainingExcess")
                        .HasPrecision(18, 5)
                        .HasColumnType("decimal(18,5)");

                    b.Property<string>("Salesman")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceBulkSoNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("TotalManufacturedQuantity")
                        .HasPrecision(18, 5)
                        .HasColumnType("decimal(18,5)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryDate", "ItemCode")
                        .HasDatabaseName("IX_Excess_Date_Item");

                    b.HasIndex("SourceBulkSoNumber", "ItemCode")
                        .IsUnique()
                        .HasDatabaseName("UQ_Excess_BulkSO_Item");

                    b.ToTable("Excesses");
                });

            modelBuilder.Entity("EnterpriseAuth.Api.Core.Domain.Entities.GlobalSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Action");

                    b.Property<string>("LastUpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("LastUpdatedBy");

                    b.Property<string>("SettingKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("SettingKey");

                    b.Property<string>("SettingValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SettingValue");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.ToTable("GlobalSettings");
                });

            modelBuilder.Entity("EnterpriseAuth.Api.Core.Domain.Entities.LabelAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("CustomerName");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("DeviceId");

                    b.Property<bool>("IsOfflineCreated")
                        .HasColumnType("bit")
                        .HasColumnName("IsOfflineCreated");

                    b.Property<string>("LabelId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LabelId");

                    b.Property<string>("LabelType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LabelType");

                    b.Property<string>("ManifestJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ManifestJson");

                    b.Property<string>("PrintedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("PrintedBy");

                    b.Property<string>("ProductCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ProductCode");

                    b.Property<string>("ReferenceNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ReferenceNumber");

                    b.Property<decimal>("TotalWeight")
                        .HasPrecision(18, 5)
                        .HasColumnType("decimal(18,5)")
                        .HasColumnName("TotalWeight");

                    b.HasKey("Id");

                    b.HasIndex("LabelId")
                        .IsUnique();

                    b.ToTable("LabelAudits");
                });

            modelBuilder.Entity("EnterpriseAuth.Api.Core.Domain.Entities.OrderShipmentStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsPreparedForShipment")
                        .HasColumnType("bit")
                        .HasColumnName("IsPreparedForShipment");

                    b.Property<bool>("IsValidated")
                        .HasColumnType("bit")
                        .HasColumnName("IsValidated");

                    b.Property<string>("SoNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("SoNumber");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("UpdatedBy");

                    b.HasKey("Id");

                    b.HasIndex("SoNumber")
                        .IsUnique()
                        .HasDatabaseName("UQ_OrderShipmentStatus_SoNumber");

                    b.ToTable("OrderShipmentStatus");
                });

            modelBuilder.Entity("EnterpriseAuth.Api.Core.Domain.Entities.OrderStatusHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ChangedAt");

                    b.Property<string>("ChangedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ChangedBy");

                    b.Property<string>("SoNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("SoNumber");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("Status");

                    b.HasKey("Id");

                    b.HasIndex("SoNumber")
                        .HasDatabaseName("IX_OrderStatusHistory_SoNumber");

                    b.ToTable("OrderStatusHistory");
                });

            modelBuilder.Entity("EnterpriseAuth.Api.Core.Domain.Entities.ProductionLineState", b =>
                {
                    b.Property<Guid>("SalesOrderLineId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("SalesOrderLineId");

                    b.Property<bool>("IsLineCompleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsLineCompleted");

                    b.Property<bool>("IsPrepared")
                        .HasColumnType("bit")
                        .HasColumnName("IsPrepared");

                    b.Property<bool>("IsValidated")
                        .HasColumnType("bit")
                        .HasColumnName("IsValidated");

                    b.Property<Guid?>("LastScanId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("LastScanId");

                    b.Property<decimal>("TotalEaQty")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("TotalEaQty");

                    b.Property<decimal>("TotalManufacturedQty")
                        .HasPrecision(18, 5)
                        .HasColumnType("decimal(18,5)")
                        .HasColumnName("TotalManufacturedQty");

                    b.Property<decimal>("TotalPreparedQty")
                        .HasPrecision(18, 5)
                        .HasColumnType("decimal(18,5)")
                        .HasColumnName("TotalPreparedQty");

                    b.Property<decimal>("TotalValidatedQty")
                        .HasPrecision(18, 5)
                        .HasColumnType("decimal(18,5)")
                        .HasColumnName("TotalValidatedQty");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("SalesOrderLineId");

                    b.ToTable("ProductionLineStates");
                });

            modelBuilder.Entity("EnterpriseAuth.Api.Core.Domain.Entities.ProductionScanTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("Barcode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Barcode");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CreatedBy");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("DeviceId");

                    b.Property<decimal?>("EaQuantity")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("EaQuantity");

                    b.Property<Guid?>("EodProcessAuditId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("EodProcessAuditId");

                    b.Property<Guid?>("EodTransactionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("ExcludeFromEod")
                        .HasColumnType("bit")
                        .HasColumnName("ExcludeFromEod");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit")
                        .HasColumnName("IsArchived");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<bool>("IsEodProcessed")
                        .HasColumnType("bit")
                        .HasColumnName("IsEodProcessed");

                    b.Property<string>("ItemStatus")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ItemStatus");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Location");

                    b.Property<string>("LotNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("LotNumber");

                    b.Property<Guid>("SalesOrderLineId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("SalesOrderLineId");

                    b.Property<decimal>("ScanAmountKg")
                        .HasPrecision(18, 5)
                        .HasColumnType("decimal(18,5)")
                        .HasColumnName("ScanAmountKg");

                    b.Property<string>("SyncId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("SyncId");

                    b.HasKey("Id");

                    b.HasIndex("EodProcessAuditId");

                    b.HasIndex("SyncId")
                        .IsUnique();

                    b.HasIndex("SalesOrderLineId", "IsDeleted", "IsArchived");

                    b.ToTable("ProductionScanTransactions");
                });

            modelBuilder.Entity("EnterpriseAuth.Api.Core.Domain.Entities.SalesOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("CustomerCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CustomerCode");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("CustomerName");

                    b.Property<DateTime?>("DeliveryDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeliveryDate");

                    b.Property<bool>("ExcludeFromEod")
                        .HasColumnType("bit")
                        .HasColumnName("ExcludeFromEod");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit")
                        .HasColumnName("IsArchived");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("bit")
                        .HasColumnName("IsProcessed");

                    b.Property<DateTime?>("OrderDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("OrderDate");

                    b.Property<string>("PoNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("PoNumber");

                    b.Property<string>("Rep0")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Rep0");

                    b.Property<string>("Rep1")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Rep1");

                    b.Property<string>("Salesman")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Salesman");

                    b.Property<string>("Site")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Site");

                    b.Property<string>("SourceOrderId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("SourceOrderId");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("SourceSystem");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("Status");

                    b.Property<string>("TargetLorry")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TargetLorry");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("SourceOrderId")
                        .IsUnique();

                    b.HasIndex("SourceSystem", "Status", "IsArchived");

                    b.ToTable("SalesOrders");
                });

            modelBuilder.Entity("EnterpriseAuth.Api.Core.Domain.Entities.SalesOrderLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Description");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ItemCode");

                    b.Property<int>("LineNumber")
                        .HasColumnType("int")
                        .HasColumnName("LineNumber");

                    b.Property<int>("LineStatus")
                        .HasColumnType("int")
                        .HasColumnName("LineStatus");

                    b.Property<decimal>("OrderedQuantity")
                        .HasPrecision(18, 5)
                        .HasColumnType("decimal(18,5)")
                        .HasColumnName("OrderedQuantity");

                    b.Property<Guid>("SalesOrderId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("SalesOrderId");

                    b.Property<string>("TargetLocation")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Location");

                    b.Property<string>("TargetLot")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Lot");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Unit");

                    b.HasKey("Id");

                    b.HasIndex("SalesOrderId", "ItemCode");

                    b.ToTable("SalesOrderLines");
                });

            modelBuilder.Entity("EnterpriseAuth.Api.Core.Domain.Entities.Staging", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("bit")
                        .HasColumnName("IsProcessed");

                    b.Property<string>("LotNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("LotNumber");

                    b.Property<string>("ZBPCORD_0")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("ZBPCORD_0");

                    b.Property<int>("ZCFMFLG_0")
                        .HasColumnType("int")
                        .HasColumnName("ZCFMFLG_0");

                    b.Property<DateTime?>("ZDLVDAT_0")
                        .HasColumnType("datetime2")
                        .HasColumnName("ZDLVDAT_0");

                    b.Property<string>("ZITMDES_0")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ZITMDES_0");

                    b.Property<string>("ZITMREF_0")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ZITMREF_0");

                    b.Property<string>("ZLOCFCY_0")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ZLOCFCY_0");

                    b.Property<string>("ZLOC_0")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ZLOC_0");

                    b.Property<decimal>("ZQTY_0")
                        .HasPrecision(18, 5)
                        .HasColumnType("decimal(18,5)")
                        .HasColumnName("ZQTY_0");

                    b.Property<string>("ZREC_0")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("ZREC_0");

                    b.Property<string>("ZSALFCY_0")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("ZSALFCY_0");

                    b.Property<string>("ZSAU_0")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("ZSAU_0");

                    b.Property<string>("ZSDHNUM_0")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("ZSDHNUM_0");

                    b.Property<string>("ZSDHTYP_0")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("ZSDHTYP_0");

                    b.Property<DateTime?>("ZSHIDAT_0")
                        .HasColumnType("datetime2")
                        .HasColumnName("ZSHIDAT_0");

                    b.Property<string>("ZSOHNUM_0")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("ZSOHNUM_0");

                    b.Property<int>("ZSOPLIN_0")
                        .HasColumnType("int")
                        .HasColumnName("ZSOPLIN_0");

                    b.Property<string>("ZSTOFCY_0")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("ZSTOFCY_0");

                    b.Property<string>("ZSUR_0")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("ZSUR_0");

                    b.Property<string>("ZVACITM_0")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ZVACITM_0");

                    b.HasKey("Id");

                    b.HasIndex("ZSOHNUM_0");

                    b.HasIndex("IsProcessed", "ZSOHNUM_0")
                        .HasDatabaseName("IX_Staging_EOD_Processing");

                    b.ToTable("Staging");
                });

            modelBuilder.Entity("EnterpriseAuth.Api.Core.Domain.Entities.StagingEod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfManufacturing")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("EaQuantity")
                        .HasPrecision(18, 5)
                        .HasColumnType("decimal(18,5)");

                    b.Property<Guid?>("EodTransactionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFpp")
                        .HasColumnType("bit");

                    b.Property<string>("ItemStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Location2")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Location3")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LotNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("TotalManufacturedQuantity")
                        .HasPrecision(18, 5)
                        .HasColumnType("decimal(18,5)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("WorkOrderNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("WorkOrderNumber");

                    b.HasIndex("IsProcessed", "WorkOrderNumber")
                        .HasDatabaseName("IX_StagingEod_IsProcessed_WorkOrder");

                    b.ToTable("StagingEod");
                });

            modelBuilder.Entity("EnterpriseAuth.Api.Core.Domain.Entities.X3SoapAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Identifier")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("bit");

                    b.Property<string>("RequestPayload")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponsePayload")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TriggeredBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("X3SoapAudits");
                });

            modelBuilder.Entity("EnterpriseAuth.Api.Core.Domain.Entities.ProductionLineState", b =>
                {
                    b.HasOne("EnterpriseAuth.Api.Core.Domain.Entities.SalesOrderLine", "OrderLine")
                        .WithOne()
                        .HasForeignKey("EnterpriseAuth.Api.Core.Domain.Entities.ProductionLineState", "SalesOrderLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderLine");
                });

            modelBuilder.Entity("EnterpriseAuth.Api.Core.Domain.Entities.ProductionScanTransaction", b =>
                {
                    b.HasOne("EnterpriseAuth.Api.Core.Domain.Entities.EodProcessAudit", "EodProcessAudit")
                        .WithMany()
                        .HasForeignKey("EodProcessAuditId");

                    b.HasOne("EnterpriseAuth.Api.Core.Domain.Entities.SalesOrderLine", "OrderLine")
                        .WithMany()
                        .HasForeignKey("SalesOrderLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EodProcessAudit");

                    b.Navigation("OrderLine");
                });

            modelBuilder.Entity("EnterpriseAuth.Api.Core.Domain.Entities.SalesOrderLine", b =>
                {
                    b.HasOne("EnterpriseAuth.Api.Core.Domain.Entities.SalesOrder", "Order")
                        .WithMany("Lines")
                        .HasForeignKey("SalesOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("EnterpriseAuth.Api.Core.Domain.Entities.SalesOrder", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
